### ISSUE TITLE
Please, can You add options to turn void of Limestone ant Plantmaster on and off ingame separatly

### ISSUE THREAD

**Issue by serjevski** [CubeSuite/TTMod-VoidMOLE#1]
Now I'm in beginning of game and I need Plantmatter, produced by Thresher, bit it disappears! But i don't need a lot of Limestone :)

**Comment by CubeSuite** [comment]
Surprised that the thresher isn't producing it, I'll take a look into that and also add those settings. Thanks for the feedback

**Comment by CubeSuite** [comment]
Hi again, I'm afraid I haven't been able to replicate the issue you've experienced. Given that this mod only interacts with terrain manipulation code, I believe the issue you saw was caused by another mod.

I have however, added the ability to toggle whether to void each type of resource as requested.
